name: agrocontabilapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  charts_flutter: ^0.8.1
  page_view_indicators: ^1.3.1
  dio: ^3.0.8
  flutter_mobx: ^1.0.1
  mobx: ^1.0.0
  flutter_modular: ^0.4.0
  flutter:
    sdk: flutter
  sliding_up_panel: ^1.0.0
  

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.1
  build_runner: ^1.7.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true 
  assets:
    - assets/logoapp.png
    - assets/loadingbutton.gif
  fonts:
    - family:  MyIcons
      fonts:
       - asset: fonts/MyIcons.ttf