/// Flutter icons CustomIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';

  static const IconData menu = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData menu_2 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData directions_transit = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData directions_walk = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData disc_full = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData dns = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData eject = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData email = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData enhanced_encryption = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData equalizer = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData exposure_neg_2 = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData exposure_plus_1 = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData exposure_plus_2 = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData exposure_zero = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData filter = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData filter_1 = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData filter_2 = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData filter_3 = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData find_in_page = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData find_replace = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData fingerprint = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData first_page = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData font_download = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData format_align_center = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData menu_1 = const IconData(0xf0c9, fontFamily: _kFontFam);
}
